name: hellojava
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
    # uses-material-design: true

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

  shared_preferences: ^2.3.2

  flutter_markdown: ^0.7.4+2

  google_generative_ai: ^0.4.6

  flutter_dotenv: ^5.1.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.png
    - assets/section-1-questions.json
    - assets/content/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"